[build]
  publish = "/"

# Enable clean URLs
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Handle redirects
[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

# Ensure all routes fallback to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 